export const colors = {
  pink: "#F50A48",
  pinkDark: "#C9063A",
  pinkSoft: "#FFE3EA",
  coral: "#FF7668",
  night: "#160A11",
  nightRaised: "#241019",
  nightBorder: "#3B1B28",
  paper: "#FFF7F8",
  surface: "#FFFFFF",
  surfaceWarm: "#FFF0F2",
  ink: "#2B1420",
  inkMuted: "#735966",
  inkFaint: "#A58D98",
  border: "#EEDCE2",
  borderStrong: "#D9BEC8",
  success: "#167A58",
  successSoft: "#DDF4EA",
  warning: "#9A5C00",
  warningSoft: "#FFF0CC",
  danger: "#B4233D",
  dangerSoft: "#FCE3E7",
  info: "#3856A6",
  infoSoft: "#E6EBFA",
  white: "#FFFFFF",
} as const;

export const orderStateColor = {
  pending: colors.pink,
  accepted: colors.info,
  processing: colors.coral,
  ready: colors.warning,
  fulfilled: colors.success,
  cancelled: colors.inkFaint,
} as const;
